/*
 * generated by Xtext 2.9.2
 */
package de.wwu.pi.acse.xtext.validationexample.ui.tests;

import com.google.inject.Injector;
import de.wwu.pi.acse.xtext.validation.ui.internal.ValidationActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class ValDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ValidationActivator.getInstance().getInjector("de.wwu.pi.acse.xtext.validationexample.ValDsl");
	}

}
