/**
 * generated by Xtext 2.9.2
 */
package de.wwu.pi.acse.xtext.validationexample;

import de.wwu.pi.acse.xtext.validationexample.AbstractValDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ValDslRuntimeModule extends AbstractValDslRuntimeModule {
}
