/**
 * generated by Xtext 2.9.2
 */
package de.wwu.pi.acse.xtext.validationexample;

import de.wwu.pi.acse.xtext.validationexample.ValDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ValDslStandaloneSetup extends ValDslStandaloneSetupGenerated {
  public static void doSetup() {
    ValDslStandaloneSetup _valDslStandaloneSetup = new ValDslStandaloneSetup();
    _valDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
