/*
 * generated by Xtext 2.9.2
 */
package de.wwu.pi.acse.xtext.validationexample.parser.antlr;

import com.google.inject.Inject;
import de.wwu.pi.acse.xtext.validationexample.parser.antlr.internal.InternalValDslParser;
import de.wwu.pi.acse.xtext.validationexample.services.ValDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ValDslParser extends AbstractAntlrParser {

	@Inject
	private ValDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalValDslParser createParser(XtextTokenStream stream) {
		return new InternalValDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ValDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ValDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
