/**
 * generated by Xtext 2.9.2
 */
package de.wwu.pi.acse.xtext.validationexample.ui.contentassist;

import de.wwu.pi.acse.xtext.validationexample.ui.contentassist.AbstractValDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ValDslProposalProvider extends AbstractValDslProposalProvider {
}
