/*
 * generated by Xtext 2.9.2
 */
package de.wwu.pi.acse.xtext.validationexample.ui;

import com.google.inject.Injector;
import de.wwu.pi.acse.xtext.validation.ui.internal.ValidationActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ValDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ValidationActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ValidationActivator.getInstance().getInjector(ValidationActivator.DE_WWU_PI_ACSE_XTEXT_VALIDATIONEXAMPLE_VALDSL);
	}
	
}
