/*
 * generated by Xtext 2.9.2
 */
package de.wwu.pi.acse.xtext.validationexample.validation

import org.eclipse.xtext.validation.Check
import de.wwu.pi.acse.xtext.validationexample.valDsl.Entity
import de.wwu.pi.acse.xtext.validationexample.valDsl.ValDslPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class ValDslValidator extends AbstractValDslValidator {
	
    @Check
    def void checkNameStartsWithCapital(Entity entity) {
        if (!Character.isUpperCase(entity.name.charAt(0))) {
            warning("Name should start with a capital", 
                ValDslPackage.Literals.ENTITY__NAME)
        }
    }

	
}
