/*
 * generated by Xtext 2.9.2
 */
package de.wwu.pi.acse.xtext.validationexample


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ValDslRuntimeModule extends AbstractValDslRuntimeModule {
}
