/**
 * generated by Xtext 2.9.2
 */
package de.wwu.pi.acse.xtext.validationexample.ui;

import de.wwu.pi.acse.xtext.validationexample.ui.AbstractValDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ValDslUiModule extends AbstractValDslUiModule {
  public ValDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
